### ISSUE TITLE
Using the example from the Readme NameError

### ISSUE THREAD

**Issue by adregan** [kalasjocke/hyp#2]
I was having trouble defining my own linked section, so I copied the example out of the README and received the same error:

```
    json = PostResponder().respond(post, linked={'comments': comments})
NameError: global name 'comments' is not defined
```

`comments` should be `post['comments']` to avoid the error and properly access the object.

Submitting a pull request to update the README

**Comment by kalasjocke** [comment]
Closed via #3.
