### ISSUE TITLE
Doesn't work with Python 3; remove hard dependencies?

### ISSUE THREAD

**Issue by sloria** [kalasjocke/hyp#5]
Currently, hyp is not useable on Python 3 due to its hard dependency on schematics, which is Py2-only. 

Example test failure on Py34:

```
tests/test_schematics_adapter.py:2: in <module>
    from schematics.models import Model
../../../miniconda/envs/hyp/lib/python3.4/site-packages/schematics/models.py:6: in <module>
    from .types import BaseType
../../../miniconda/envs/hyp/lib/python3.4/site-packages/schematics/types/__init__.py:1: in <module>
    from .base import *
../../../miniconda/envs/hyp/lib/python3.4/site-packages/schematics/types/base.py:56: in <module>
    class BaseType(TypeMeta('BaseTypeBase', (object, ), {})):
../../../miniconda/envs/hyp/lib/python3.4/site-packages/schematics/types/base.py:47: in __new__
    for attr_name, attr in attrs.iteritems():
E   AttributeError: 'dict' object has no attribute 'iteritems'
```

Would it be possible to remove hyp's hard dependencies on schematics and marshmallow and instead have users opt in to their preferred serialization library?

**Comment by kalasjocke** [comment]
I think that we should. Let's remove the hard dependences and add a note about it in the readme.

**Comment by sloria** [comment]
This isn't fully resolved. If you don't have both marshmallow and schematics installed, you will get an `ImportError`.

If I have marshmallow but not schematics installed, I get an error:

``` python
>>> import hyp.responder
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/sloria/projects/python-projects/hyp/hyp/responder.py", line 5, in <module>
    from hyp.adapters.base import adapter_for
  File "/Users/sloria/projects/python-projects/hyp/hyp/adapters/base.py", line 3, in <module>
    from schematics.models import Model as SchematicsSerializer
ImportError: No module named 'schematics'
```

There are a number of ways to solve this. 

Solution 1: One simple fix would be a modfication to `adapter_for`

``` python
try:
    from hyp.adapters.schematics import Adapter as SchematicsAdapter
except ImportError:
    schematics_available = False
else:
    schematics_available = True
# ... same with marshmallow ...

def adapter_for(serializer):
    if schematic_available and issubclass(serializer, SchematicsSerializer):
        return SchematicsAdapter
    elif marshmallow_available and issubclass(serializer, MarshmallowSerializer):
        return MarshmallowAdapter
    else:
        raise NotImplementedError()
```

The advantage of this is that it is backwards-compatible. Disadvantage is that there is no way for the user to use a different adapter without modifying the hyp library.

Solution 2: Another solution would be to allow the user to specify which adapter they want to use.

``` python
# user code
class BaseResponder(Responder):
    ADAPTER = MarshmallowAdapter

class CommentResponder(BaseResponder):
    TYPE = 'comments'
    SERIALIZER = CommentSchema
```

The advantage of this is that the user could create and use their own `Adapter`.

These fixes aren't mutually exclusive; you could allow for explicit adapter selection and still support the current implicit adapter selection with `adapter_for`. 

I would gladly send a PR implementing either or both of these solutions; just wanted to get your feedback first!

**Comment by kalasjocke** [comment]
Thanks for noticing this. I was a bit to fast on the trigger yesterday night. On the positive note of things I haven't released a version to PyPi yet.

I think it's fine to break backwards compatibility in such an early version of the library.

Let's go with your second solution. Perhaps with a twist. What do you think of shipping the library with two base responders, one `SchematicsResponder` and one `MarshmallowResponder` that does the `ADAPTER` selection for you so you don't have to care about implementation details?

**Comment by sloria** [comment]
+1 to the library-specific base `Responders`. 

I will work on this this evening.

**Comment by sloria** [comment]
Given that all imports of third party libraries must be isolated from the base `hyp` code, how about the following module organization:
- `hyp.base`: Contains base classes `BaseResponder` and `BaseAdapter`.
- `hyp.marshmallow`: Contains `Responder` and `Adapter` that use marshmallow.
- `hyp.schematics`: Contains `Responder` and `Adapter` that use schematics.

Also, `adapter_for` will be removed, as it is no longer necessary with the library-specific `Responders`.

What are your thoughts?

**Comment by kalasjocke** [comment]
@sloria Sounds like a great plan, I really like getting rid of `adapter_for` :+1:

**Comment by sloria** [comment]
Excellent. I will work on this today.
